### ISSUE TITLE
No requirements are displayed in projects without GitHub connection

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/RequirementsBazaar-WebFrontend#167]
The following error shows up in the console multiple times:
```
TypeError: _ctx.showButtonGitHub is not a function
    at RequirementCard.vue:5:156
    at renderFnWithContext (runtime-core.esm-bundler.js:1125:21)
    at renderSlot (runtime-core.esm-bundler.js:6701:55)
    at Proxy.render (card.esm.js:37:13)
    at renderComponentRoot (runtime-core.esm-bundler.js:1168:44)
    at componentEffect (runtime-core.esm-bundler.js:5214:57)
    at reactiveEffect (reactivity.esm-bundler.js:42:24)
    at effect (reactivity.esm-bundler.js:17:9)
    at setupRenderEffect (runtime-core.esm-bundler.js:5167:27)
    at mountComponent (runtime-core.esm-bundler.js:5126:9)
```
Requirements are displayed correctly in projects with GitHub connection

**Comment by fxjordan** [comment]
Root cause seems to be:
```
ErrorHandler.ts:28 TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at setup (RequirementCard.vue:134:48)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7154:29)
    at setupComponent (runtime-core.esm-bundler.js:7110:11)
    at mountComponent (runtime-core.esm-bundler.js:5109:13)
    at processComponent (runtime-core.esm-bundler.js:5084:17)
    at patch (runtime-core.esm-bundler.js:4690:21)
    at mountChildren (runtime-core.esm-bundler.js:4874:13)
    at mountElement (runtime-core.esm-bundler.js:4795:17)
```

The code only checks the existence of the `additionalProperties` property on requirements JSON and assumes properties like `issue_number` etc. exist

**Comment by fxjordan** [comment]
Actually, the problems was that 'additionalProperties was `null` but the code only checked for `undefined` (fixed in https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/commit/0a663273a8a1a9d5baa387cfd8e50407a9c07378)
